
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-01
owner: ucsb-cs156-f24
repo_name: team02-f24-01
pull_requests: [{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincentc0202-menuitem-team03","number":127,"title":"UCSBDiningCommonsMenuItem Integration tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/127"},{"author":{"id":"MDQ6VXNlcjYxMzk0NTgx","is_bot":false,"login":"Neamal","name":"Junhyung Yoon"},"headRefName":"junhyung-menuitemreview-team03","number":123,"title":"Junhyung menuitemreview team03 Integration Test","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/123"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"Cam-HelpRequest-Index","number":120,"title":"Cam help request index","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/120"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-orgs-e2e","number":119,"title":"Created organization end to end test","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/119"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"Cam-HelpRequest-Tables","number":118,"title":"Made table component for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/118"},{"author":{"id":"U_kgDOBcsK0A","is_bot":false,"login":"raychen179","name":""},"headRefName":"team03-articlesNew","number":117,"title":"Integration Tests for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/117"},{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"TEAM03-112-e2e-tests-for-recommendation-requests","number":113,"title":"TEAM03-112: End to End tests for recommendation requests","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/113"},{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"TEAM03-107-integration-tests-for-recommendation-requests","number":111,"title":"TEAM03-107 Added Integration test for get element by id for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/111"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cam-HelpRequest-Component-tests","number":87,"title":"Made form, tests, and storybook for helprequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/87"}]
