
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-01
owner: ucsb-cs156-f24
repo_name: team02-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"TEAM03-107-integration-tests-for-recommendation-requests","number":111,"title":"TEAM03-107 Added Integration test for get element by id for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/111"},{"author":{"id":"MDQ6VXNlcjYxMzk0NTgx","is_bot":false,"login":"Neamal","name":"Junhyung Yoon"},"headRefName":"junhyung-menuitemreview-editpage","number":108,"title":"Junhyung menuitemreview editpage","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/108"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincentc0202-menuitem-edit","number":99,"title":"TEAM02-15: UCSBDiningCommonsMenuItem Edit page finished","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/99"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincentc0202-menuitem-index","number":97,"title":"TEAM02-14: menuitem index page created","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/97"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincentc0202-menuitem-create","number":91,"title":"TEAM02-13: UCSBDiningCommonsMenuItem Create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/91"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cam-HelpRequest-Component-tests","number":87,"title":"Made form, tests, and storybook for helprequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/87"}]
