
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-01
owner: ucsb-cs156-f24
repo_name: team02-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-create-org-fixtures","number":63,"title":"Added organization fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/63"},{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-ucsborgs-copy-backend","number":62,"title":"Copied over backend files from team01 for UCSBOrganization","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/62"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincentc0202-menuitem-copy-backend","number":61,"title":"TEAM02-08: Added the backend files for menuItem","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/61"}]
