
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-01
owner: ucsb-cs156-f24
repo_name: team02-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa Weston"},"headRefName":"TEAM02-30-copy-placeholders-for-recommendation-request-pages","number":83,"title":"TEAM02-30opy Placeholders for RecommendationRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/83"},{"author":{"id":"MDQ6VXNlcjYxMzk0NTgx","is_bot":false,"login":"Neamal","name":"Junhyung Yoon"},"headRefName":"junhyung-menuitemreview-fixtures1","number":77,"title":"fixtures for menuitemreview including prettier formatting","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/77"},{"author":{"id":"U_kgDOBcsK0A","is_bot":false,"login":"raychen179","name":""},"headRefName":"Raymond-Articles","number":75,"title":"Raymond Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/75"},{"author":{"id":"MDQ6VXNlcjYxMzk0NTgx","is_bot":false,"login":"Neamal","name":"Junhyung Yoon"},"headRefName":"junhyung-menuitemreview-backend","number":69,"title":"CRUD Backend for MenuItemReview - Junhyung Yoon","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/69"}]
