
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-01
owner: ucsb-cs156-f24
repo_name: team02-f24-01
pull_requests: [{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cam-team03-E2E","number":136,"title":"Cam team03 e2e","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/136"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cam-team03-initial-branch","number":135,"title":"Integration Test works for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/135"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cam-helprequest-placeholders-create-index-edit","number":131,"title":"Cam helprequest placeholders create index edit","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/131"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"Cam-HelpRequest-Index","number":120,"title":"Cam help request index","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/120"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"Cam-HelpRequest-Tables","number":118,"title":"Made table component for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/118"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cam-HelpRequest-Component-tests","number":87,"title":"Made form, tests, and storybook for helprequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-01/pull/87"}]
